### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by stylemessiah** [AndroPlus-org/zygisk-devicefaker#1]
new to compiling but spent hours trying.....paths etc done...heart surgery would be easier to learn

closest i seem to have gotten is:

cd .\zygisk\
ndk-build.cmd
c:/android-ndk-r25/build/../build/core/build-binary.mk:586: Android NDK: Module devicefaker depends on undefined modules: cxx
c:/android-ndk-r25/build/../build/core/build-binary.mk:599: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.

please is there a precompiled version for testing?

**Comment by AndroPlus-org** [comment]
Did you run this command after git clone?
You have to run this to get libcxx codes.
`git submodule update --init --recursive`

Anyway this module somehow conflicts with other Zygisk module in my env now, so maybe it won't work...

**Comment by stylemessiah** [comment]
No, i didnt, because its not mentioned anywhere in your doc :)

**Comment by AndroPlus-org** [comment]
It was in "How to build" section, though.
https://github.com/AndroPlus-org/zygisk-devicefaker#how-to-build

**Comment by stylemessiah** [comment]
I read the building section that was the first one, and stopped
there....because it said build....

Assume people have never built before is a good rule :)

**Comment by stylemessiah** [comment]
git submodule update --init --recursive completes
bash build .sh on Windows 10 WSL gives following error:

me@DESKTOP-7ROLGE9:/mnt/c/Users/Me/StudioProjects/zygisk-devicefaker$ bash build.sh
build.sh: line 2: $'\r': command not found
build.sh: line 3: $'\r': command not found
build.sh: line 5: $'\r': command not found
build.sh: line 6: cd: $'.\r': No such file or directory
build.sh: line 7: $'\r': command not found
build.sh: line 8: pushd: $'zygisk\r': No such file or directory
build.sh: line 19: syntax error near unexpected token `$'do\r''
'uild.sh: line 19: `do

**Comment by AndroPlus-org** [comment]
Somehow your build.sh is "CR + LF" EOL, maybe because of git.exe's config (I think you selected "Checkout Windows-style, commit Unix-style line endings").
Please redownload build.sh from browser or change the file to "LF" with text editor like VS Code.

**Comment by stylemessiah** [comment]
fixed with notepad++....

but then its on to more nonsense- you make it sound so simple with 2 commands

root@DESKTOP-7ROLGE9:/mnt/c/Users/Me/StudioProjects/zygisk-devicefaker# bash build.sh
/mnt/c/Users/Me/StudioProjects/zygisk-devicefaker/zygisk /mnt/c/Users/Me/StudioProjects/zygisk-devicefaker
build.sh: line 14: /opt/android_sdk/ndk/21.4.7075529/ndk-build: No such file or directory
/mnt/c/Users/Me/StudioProjects/zygisk-devicefaker
cp: cannot stat 'zygisk/libs/arm64-v8a/libdevicefaker.so': No such file or directory
cp: cannot stat 'zygisk/libs/armeabi-v7a/libdevicefaker.so': No such file or directory
cp: cannot stat 'zygisk/libs/x86/libdevicefaker.so': No such file or directory
cp: cannot stat 'zygisk/libs/x86_64/libdevicefaker.so': No such file or directory
/mnt/c/Users/Me/StudioProjects/zygisk-devicefaker/magisk /mnt/c/Users/Me/StudioProjects/zygisk-devicefaker
build.sh: line 26: zip: command not found

NDK is definitely installed (via latest Android Studio - both installed fresh last night) and repo cloned within Android Studio, why it chooses to stuff up line endings is anyones guess - this is nonsense, how does anyone work like this? because i ticked it last night and ive just reinstalled it, i have no idea why zip not showing up

Honestly, heart surgery would be easier....this is batshit level crazy, ive developed in java etc in the dark ages and it was more sane than this shit....

**Comment by stylemessiah** [comment]
Please tell me you have a compiled version i can test, because at 51, i dont have enough years left to try this via compiling

**Comment by AndroPlus-org** [comment]
Here's the compiled version.
https://github.com/AndroPlus-org/zygisk-devicefaker/releases/download/v1/devicefaker-zygisk-v01.zip

**Comment by stylemessiah** [comment]
Appreciated :)

I tried downloading ndk separately, unzipping to c: and changing path to call for it in build.sh but yet more nonsense :)

your kind share of the compiled module will shorten the war by years and save many lives :)

**Comment by stylemessiah** [comment]
Last question, i promise, is the device type hard coded or will the module take say a manufacturer prop from the system.prop and apply that on the fly to the listed app(s)?

**Comment by AndroPlus-org** [comment]
It's hard coded here:
https://github.com/AndroPlus-org/zygisk-devicefaker/blob/master/zygisk/jni/module.cpp#L157
